import express from 'express';
import crypto from 'crypto';
import prisma from '../prisma';

const router = express.Router();

// Auth Helpers
const hashPassword = (password: string): string => {
    const salt = crypto.randomBytes(16).toString('hex');
    const hash = crypto.pbkdf2Sync(password, salt, 1000, 64, 'sha512').toString('hex');
    return `${salt}:${hash}`;
};

const verifyPassword = (password: string, storedHash: string): boolean => {
    if (!storedHash.includes(':')) return false;
    const [salt, hash] = storedHash.split(':');
    const verifyHash = crypto.pbkdf2Sync(password, salt, 1000, 64, 'sha512').toString('hex');
    return hash === verifyHash;
};


// Auth Routes
router.post('/register', async (req, res) => {
    try {
        const { email, password, name } = req.body;

        // Check existing
        const existingUser = await prisma.user.findUnique({
            where: { email }
        });

        if (existingUser) {
            res.status(400).json({ error: 'Email already exists' });
            return;
        }

        const hashedPassword = hashPassword(password);
        const role = email === 'admin@vinpart.vn' ? 'ADMIN' : 'USER';
        // id is auto-generated by Prisma if using @default(cuid())

        const user = await prisma.user.create({
            data: {
                email,
                password: hashedPassword,
                name,
                role
            }
        });

        res.json({
            id: user.id,
            email: user.email,
            name: user.name,
            role: user.role.toLowerCase()
        });

    } catch (error) {
        console.error('Register error:', error);
        res.status(500).json({ error: 'Registration failed' });
    }
});


router.post('/login', async (req, res) => {
    try {
        const { email, password } = req.body;
        const cleanEmail = email ? email.trim().toLowerCase() : '';
        console.log(`Login attempt for: '${cleanEmail}'`);

        const user = await prisma.user.findUnique({
            where: { email: cleanEmail }
        });

        if (!user) {
            console.log(`User not found: '${cleanEmail}'`);
            res.status(401).json({ error: 'Invalid credentials' });
            return;
        }

        console.log(`User found: ${user.email}, Role: ${user.role}`);
        console.log(`Stored hash: ${user.password}`);

        const isValid = verifyPassword(password, user.password);
        console.log(`Password valid: ${isValid}`);

        if (!isValid) {
            console.log('Password verification failed');
            res.status(401).json({ error: 'Invalid credentials' });
            return;
        }

        res.json({
            id: user.id,
            email: user.email,
            name: user.name,
            role: user.role.toLowerCase()
        });

    } catch (error) {
        console.error('Login error:', error);
        res.status(500).json({ error: 'Login failed' });
    }
});

export default router;
