
import 'dotenv/config';
import { Pool } from 'pg';

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false }
});

async function main() {
    const client = await pool.connect();
    try {
        console.log('🔌 Connected to database');

        // This is the hash for "admin123" generated by our reproduction script
        const newHash = '9c0d507f230a41ca8643c1d544533a73:f3bc5d45889ec4165d066edfc530344803fc895e156c6a05a6ad1fd4e37ad26bd0b170c44b33728056e20641c51c69a792b0b11cf4b8a16f8e2dea012d32';

        console.log('🔄 Updating admin password...');
        const result = await client.query(
            'UPDATE users SET password = $1 WHERE email = $2 RETURNING email',
            [newHash, 'admin@vinhpart.vn']
        );

        if (result.rowCount === 0) {
            console.log('⚠️  Admin user "admin@vinhpart.vn" not found. Nothing updated.');
        } else {
            console.log(`✅ Successfully updated password for user: ${result.rows[0].email}`);
        }

    } catch (error) {
        console.error('❌ Error updating password:', error);
    } finally {
        client.release();
        await pool.end();
    }
}

main();
